### ISSUE TITLE
BSOD - Driver manual mapping other drivers

### ISSUE THREAD

**Issue by mrtiggles5** [DarthTon/Blackbone#108]
I am having issues with manually mapping my driver with the Blackbone driver. Usually I blue screen with the error "PAGE_FAULT_IN_NONPAGED_AREA". 
Any ideas on how to fix this?

**Comment by DarthTon** [comment]
Any memory dump available?

**Comment by staticinvocation** [comment]
Does your driver have any imports outside of ntoskrnl.exe (or equivalent)?

**Comment by Uysse** [comment]
Ran into the same problem running the Test app at "TestRemoteMem" function.
Windows 10 1607 version x64.
Dump here : 
http://www.filedropper.com/111216-5750-01

**Comment by staticinvocation** [comment]
@Uysse your issue was fixed in #100 DarthTon did not update the binaries in the repo.  Compiling BlackBoneDrv from source should fix your issue.

**Comment by Uysse** [comment]
I compiled BlackBoneDrv10 and can confirm that it indeed fixed the BSOD problem. Just one problem remains on the logs it says : "BlackBone : NativeLdr : LdrHeapBase not found".
Got any idea what's wrong ?

**Comment by DarthTon** [comment]
Apparently AU update really was the issue. I've updated compiled binaries now.
@UIysse that happens when you attach to a not yet initialized (suspended on creation) process. Can be ignored because BB uses another memory instead.
